/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.danielcampos.redgym.proyecto;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import com.danielcampos.redgym.proyecto.Ingreso;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.border.Border;

/**
 *
 * @author Daniel Gerardo Campos García
 * Class JInternalFrame Menu se crea para visualizar la interface del sistema y sus respectivas funciones
 * Variables: Excritura de camello abreviando su tipo de componente seguido de su nombre de variable
 * Metodos: Exritura de camello (El nombre debe se ser sacado de la funcion que tiene el metodo)
 * 
 * 
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Usario
     */
    Ingreso in = new Ingreso();
    

    public Menu() {
       
        initComponents();
        
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/pesa.png")).getImage()); 
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu1 = new javax.swing.JDesktopPane();
        miniMenu = new javax.swing.JLabel();
        btnCerrarMenu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelGuardar = new javax.swing.JPanel();
        IconGuardar = new javax.swing.JLabel();
        PanelPlan = new javax.swing.JPanel();
        IconPlan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNom = new javax.swing.JLabel();
        PanelProducto = new javax.swing.JPanel();
        IconProductos = new javax.swing.JLabel();
        PanelClientes = new javax.swing.JPanel();
        IconClientes = new javax.swing.JLabel();
        PanelVentas = new javax.swing.JPanel();
        IconVentas = new javax.swing.JLabel();
        PanelEmpleados = new javax.swing.JPanel();
        IconEmpleado = new javax.swing.JLabel();
        PanelIngreso = new javax.swing.JPanel();
        IconIngreso = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelControl = new javax.swing.JPanel();
        IconControl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu1.setBackground(new java.awt.Color(255, 255, 255));
        Menu1.setEnabled(false);
        Menu1.setMaximumSize(new java.awt.Dimension(0, 0));

        miniMenu.setBackground(new java.awt.Color(255, 255, 255));
        miniMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        miniMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        miniMenu.setText("-");
        miniMenu.setPreferredSize(new java.awt.Dimension(10, 14));
        miniMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuMouseExited(evt);
            }
        });

        btnCerrarMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarMenu.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnCerrarMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarMenu.setText("X");
        btnCerrarMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarMenu.setIconTextGap(0);
        btnCerrarMenu.setPreferredSize(new java.awt.Dimension(10, 14));
        btnCerrarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMenuMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.jpg"))); // NOI18N

        Menu1.setLayer(miniMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Menu1.setLayer(btnCerrarMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Menu1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Menu1Layout = new javax.swing.GroupLayout(Menu1);
        Menu1.setLayout(Menu1Layout);
        Menu1Layout.setHorizontalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu1Layout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addComponent(miniMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Menu1Layout.setVerticalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu1Layout.createSequentialGroup()
                .addGroup(Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(miniMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 750, 580));

        PanelGuardar.setBackground(new java.awt.Color(0, 117, 155));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        IconGuardar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        IconGuardar.setForeground(new java.awt.Color(255, 255, 255));
        IconGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconGuardar.setText("Respaldar");

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(PanelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 220, 50));

        PanelPlan.setBackground(new java.awt.Color(0, 117, 155));
        PanelPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelPlanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelPlanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelPlanMouseExited(evt);
            }
        });

        IconPlan.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        IconPlan.setForeground(new java.awt.Color(255, 255, 255));
        IconPlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconPlan.setText("Planes");

        javax.swing.GroupLayout PanelPlanLayout = new javax.swing.GroupLayout(PanelPlan);
        PanelPlan.setLayout(PanelPlanLayout);
        PanelPlanLayout.setHorizontalGroup(
            PanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelPlanLayout.setVerticalGroup(
            PanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sin.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        txtNom.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtNom.setForeground(new java.awt.Color(0, 102, 255));
        txtNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(txtNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        PanelProducto.setBackground(new java.awt.Color(0, 117, 155));
        PanelProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelProductoMouseExited(evt);
            }
        });

        IconProductos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        IconProductos.setForeground(new java.awt.Color(255, 255, 255));
        IconProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconProductos.setText("Productos");

        javax.swing.GroupLayout PanelProductoLayout = new javax.swing.GroupLayout(PanelProducto);
        PanelProducto.setLayout(PanelProductoLayout);
        PanelProductoLayout.setHorizontalGroup(
            PanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelProductoLayout.setVerticalGroup(
            PanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(PanelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 50));

        PanelClientes.setBackground(new java.awt.Color(0, 117, 155));
        PanelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelClientesMouseExited(evt);
            }
        });

        IconClientes.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        IconClientes.setForeground(new java.awt.Color(255, 255, 255));
        IconClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconClientes.setText("Clientes");

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(PanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 50));

        PanelVentas.setBackground(new java.awt.Color(0, 117, 155));
        PanelVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelVentasMouseExited(evt);
            }
        });

        IconVentas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        IconVentas.setForeground(new java.awt.Color(255, 255, 255));
        IconVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconVentas.setText("Ventas");

        javax.swing.GroupLayout PanelVentasLayout = new javax.swing.GroupLayout(PanelVentas);
        PanelVentas.setLayout(PanelVentasLayout);
        PanelVentasLayout.setHorizontalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelVentasLayout.setVerticalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(PanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 50));

        PanelEmpleados.setBackground(new java.awt.Color(0, 117, 155));
        PanelEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEmpleadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEmpleadosMouseExited(evt);
            }
        });

        IconEmpleado.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        IconEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        IconEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconEmpleado.setText("Nuevo Entrenador");

        javax.swing.GroupLayout PanelEmpleadosLayout = new javax.swing.GroupLayout(PanelEmpleados);
        PanelEmpleados.setLayout(PanelEmpleadosLayout);
        PanelEmpleadosLayout.setHorizontalGroup(
            PanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelEmpleadosLayout.setVerticalGroup(
            PanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(PanelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 50));

        PanelIngreso.setBackground(new java.awt.Color(0, 117, 155));
        PanelIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelIngresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelIngresoMouseExited(evt);
            }
        });

        IconIngreso.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        IconIngreso.setForeground(new java.awt.Color(255, 255, 255));
        IconIngreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconIngreso.setText("Login Clientes");

        javax.swing.GroupLayout PanelIngresoLayout = new javax.swing.GroupLayout(PanelIngreso);
        PanelIngreso.setLayout(PanelIngresoLayout);
        PanelIngresoLayout.setHorizontalGroup(
            PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelIngresoLayout.setVerticalGroup(
            PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(PanelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel2.setText("Version 1.0.0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel3.setText("Email.- danielgecampos97@hotmail.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 529, 220, -1));

        PanelControl.setBackground(new java.awt.Color(0, 117, 155));
        PanelControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelControlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelControlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelControlMouseExited(evt);
            }
        });

        IconControl.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        IconControl.setForeground(new java.awt.Color(255, 255, 255));
        IconControl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconControl.setText("Control");

        javax.swing.GroupLayout PanelControlLayout = new javax.swing.GroupLayout(PanelControl);
        PanelControl.setLayout(PanelControlLayout);
        PanelControlLayout.setHorizontalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconControl, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelControlLayout.setVerticalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconControl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(PanelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 220, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     Se utiliza para que al momento que dejes precionado con el click al frame se pueda mover
     */
    private int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/img/Sin1.png"));
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        Icon icon = new ImageIcon(getClass().getResource("/img/Sin.png"));
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_jLabel1MouseExited

    private void PanelPlanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPlanMouseClicked
        
        NuevoPlanes pr = new NuevoPlanes();
        if(InternalFramesAbiertos(pr)==false){
        centrarVentana(pr);       
        Color cl = new Color(64, 205, 145);
        PanelPlan.setBackground(cl);
        Icon icon = new ImageIcon(getClass().getResource("/img/gif.gif"));
        IconPlan.setIcon(icon);
        btnCerrarMenu.setVisible(false);
        miniMenu.setVisible(false);
        PanelPlan.setEnabled(false);
        cerrarTodoMenosPlan();}
    }//GEN-LAST:event_PanelPlanMouseClicked
    
   
    /**
     * Se crea para guardar un backup de la BD y crea la carpeta si es que no existe
     * @param evt 
     * 
     */
    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        Color cl = new Color(64, 205, 145);
        PanelGuardar.setBackground(cl);
        Icon icon = new ImageIcon(getClass().getResource("/img/gif.gif"));
        IconGuardar.setIcon(icon);
        String nom=JOptionPane.showInputDialog("¿Como deseas que se llame?");
        File carpetaHaGuardar = new File("C:\\backupsistem");
            if(!carpetaHaGuardar.exists()){
                carpetaHaGuardar.mkdirs();
            }
        try {
            Conexion cc = new Conexion();
            PreparedStatement ps;
            ResultSet rs;
            Connection cn = cc.Conexion();
          
            ps = cn.prepareStatement("BACKUP Database GYM TO DISK="+"'C:\\backupsistem\\"+nom+".bak'");
           
            rs = ps.executeQuery();
         
        } catch (SQLException ex) {
             Color cll= new Color(0,117,155);
     PanelGuardar.setBackground(cll);
     
     IconGuardar.setIcon(null);
        }
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductoMouseClicked
        Color cl = new Color(64, 205, 145);
        NuevoProducto pr = new NuevoProducto();        
        if(InternalFramesAbiertos(pr)==false){
        centrarVentana(pr);
        PanelProducto.setBackground(cl);
        Icon icon = new ImageIcon(getClass().getResource("/img/gif.gif"));
        IconProductos.setIcon(icon);
        PanelProducto.setEnabled(false);
        cerrarTodoMenosProducto();}
    }//GEN-LAST:event_PanelProductoMouseClicked

    private void PanelVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVentasMouseClicked
        Color cl = new Color(64, 205, 145);
        NuevaVenta vn = new NuevaVenta();
        if(InternalFramesAbiertos(vn)==false){
        centrarVentana(vn);
        PanelVentas.setBackground(cl);
        Icon icon = new ImageIcon(getClass().getResource("/img/gif.gif"));
        IconVentas.setIcon(icon);
        PanelVentas.setEnabled(false);
        cerrarTodoMenosVentas();}
    }//GEN-LAST:event_PanelVentasMouseClicked

    private void PanelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelClientesMouseClicked
        Color cl = new Color(64, 205, 145);
        MenuCliente cc = new MenuCliente();
        if(InternalFramesAbiertos(cc)==false){
        centrarVentana(cc);
        btnCerrarMenu.setVisible(false);
        miniMenu.setVisible(false);
        PanelClientes.setBackground(cl);
        Icon icon = new ImageIcon(getClass().getResource("/img/gif.gif"));
        IconClientes.setIcon(icon);
        PanelClientes.setEnabled(false);
        cerrarTodoMenosClientes();}
    }//GEN-LAST:event_PanelClientesMouseClicked

    private void PanelEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEmpleadosMouseClicked
        Color cl = new Color(64, 205, 145);
        NuevoEntrenador en = new NuevoEntrenador();
        if(InternalFramesAbiertos(en)==false){
        centrarVentana(en);
         btnCerrarMenu.setVisible(false);
        miniMenu.setVisible(false);
        PanelEmpleados.setBackground(cl);
        Icon icon = new ImageIcon(getClass().getResource("/img/gif.gif"));
        IconEmpleado.setIcon(icon);
        PanelEmpleados.setEnabled(false);
        cerrarTodoMenosEmpleados();}
    }//GEN-LAST:event_PanelEmpleadosMouseClicked

    private void PanelIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelIngresoMouseClicked
       
        Color cl = new Color(64, 205, 145);
        Ingreso en = new Ingreso();
        en.setVisible(true);
        PanelIngreso.setBackground(cl);
        Icon icon = new ImageIcon(getClass().getResource("/img/gif.gif"));
        IconIngreso.setIcon(icon);
        PanelIngreso.setEnabled(false);
    }//GEN-LAST:event_PanelIngresoMouseClicked

    private void PanelEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEmpleadosMouseEntered
       IconEmpleado.setForeground(new Color(51,204,0));
    }//GEN-LAST:event_PanelEmpleadosMouseEntered

    private void PanelEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEmpleadosMouseExited
         IconEmpleado.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelEmpleadosMouseExited

    private void PanelPlanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPlanMouseEntered
        IconPlan.setForeground(new Color(51,204,0));
    }//GEN-LAST:event_PanelPlanMouseEntered

    private void PanelProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductoMouseEntered
      IconProductos.setForeground(new Color(51,204,0));
    }//GEN-LAST:event_PanelProductoMouseEntered

    private void PanelClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelClientesMouseEntered
       IconClientes.setForeground(new Color(51,204,0));
    }//GEN-LAST:event_PanelClientesMouseEntered

    private void PanelVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVentasMouseEntered
       IconVentas.setForeground(new Color(51,204,0));
    }//GEN-LAST:event_PanelVentasMouseEntered

    private void PanelIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelIngresoMouseEntered
        IconIngreso.setForeground(new Color(51,204,0));
    }//GEN-LAST:event_PanelIngresoMouseEntered

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
       IconGuardar.setForeground(new Color(51,204,0));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelPlanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPlanMouseExited
        IconPlan.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelPlanMouseExited

    private void PanelProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductoMouseExited
       IconProductos.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelProductoMouseExited

    private void PanelClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelClientesMouseExited
        IconClientes.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelClientesMouseExited

    private void PanelVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVentasMouseExited
        IconVentas.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelVentasMouseExited

    private void PanelIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelIngresoMouseExited
       IconIngreso.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelIngresoMouseExited

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
       IconGuardar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelControlMouseClicked
        
        
        EntradasYSalidas cc = new EntradasYSalidas();
        if(InternalFramesAbiertos(cc)==false){
        centrarVentana(cc);       
        Color cl = new Color(64, 205, 145);
        PanelControl.setBackground(cl);
        Icon icon = new ImageIcon(getClass().getResource("/img/gif.gif"));
        IconControl.setIcon(icon);
        PanelControl.setEnabled(false);
        cerrarTodoMenosControl();
        }
        
        
    }//GEN-LAST:event_PanelControlMouseClicked
void cerrarTodoMenosControl(){

     Color cl= new Color(0,117,155);
     PanelClientes.setBackground(cl);
     PanelEmpleados.setBackground(cl);
     PanelGuardar.setBackground(cl);
     PanelProducto.setBackground(cl);
     PanelPlan.setBackground(cl);
     PanelVentas.setBackground(cl);
     IconClientes.setIcon(null);
     IconEmpleado.setIcon(null);
     IconGuardar.setIcon(null);
     IconProductos.setIcon(null);
     IconPlan.setIcon(null);
     IconVentas.setIcon(null);
     
}
void cerrarTodoMenosClientes(){

     Color cl= new Color(0,117,155);
     PanelControl.setBackground(cl);
     PanelEmpleados.setBackground(cl);
     PanelGuardar.setBackground(cl);
     PanelProducto.setBackground(cl);
     PanelPlan.setBackground(cl);
     PanelVentas.setBackground(cl);
     IconControl.setIcon(null);
     IconEmpleado.setIcon(null);
     IconGuardar.setIcon(null);
     IconProductos.setIcon(null);
     IconPlan.setIcon(null);
     IconVentas.setIcon(null);
     
}
void cerrarTodoMenosEmpleados(){

     Color cl= new Color(0,117,155);
     PanelControl.setBackground(cl);
     PanelClientes.setBackground(cl);
     PanelGuardar.setBackground(cl);
     PanelProducto.setBackground(cl);
     PanelPlan.setBackground(cl);
     PanelVentas.setBackground(cl);
     IconControl.setIcon(null);
     IconClientes.setIcon(null);
     IconGuardar.setIcon(null);
     IconProductos.setIcon(null);
     IconPlan.setIcon(null);
     IconVentas.setIcon(null);
     
}
void cerrarTodoMenosGuardar(){

     Color cl= new Color(0,117,155);
     PanelControl.setBackground(cl);
     PanelClientes.setBackground(cl);
     PanelEmpleados.setBackground(cl);
     PanelProducto.setBackground(cl);
     PanelPlan.setBackground(cl);
     PanelVentas.setBackground(cl);
     IconControl.setIcon(null);
     IconClientes.setIcon(null);
     IconEmpleado.setIcon(null);
     IconProductos.setIcon(null);
     IconPlan.setIcon(null);
     IconVentas.setIcon(null);
     
}
void cerrarTodoMenosProducto(){

     Color cl= new Color(0,117,155);
     PanelControl.setBackground(cl);
     PanelClientes.setBackground(cl);
     PanelEmpleados.setBackground(cl);
     PanelGuardar.setBackground(cl);
     PanelPlan.setBackground(cl);
     PanelVentas.setBackground(cl);
     IconControl.setIcon(null);
     IconClientes.setIcon(null);
     IconEmpleado.setIcon(null);
     IconGuardar.setIcon(null);
     IconPlan.setIcon(null);
     IconVentas.setIcon(null);
     
}
void cerrarTodoMenosPlan(){

     Color cl= new Color(0,117,155);
     PanelControl.setBackground(cl);
     PanelClientes.setBackground(cl);
     PanelEmpleados.setBackground(cl);
     PanelProducto.setBackground(cl);
     PanelGuardar.setBackground(cl);
     PanelVentas.setBackground(cl);
     IconControl.setIcon(null);
     IconClientes.setIcon(null);
     IconEmpleado.setIcon(null);
     IconProductos.setIcon(null);
     IconGuardar.setIcon(null);
     IconVentas.setIcon(null);
     
}
void cerrarTodoMenosVentas(){

     Color cl= new Color(0,117,155);
     PanelControl.setBackground(cl);
     PanelClientes.setBackground(cl);
     PanelEmpleados.setBackground(cl);
     PanelProducto.setBackground(cl);
     PanelGuardar.setBackground(cl);
     PanelPlan.setBackground(cl);
     IconControl.setIcon(null);
     IconClientes.setIcon(null);
     IconEmpleado.setIcon(null);
     IconProductos.setIcon(null);
     IconGuardar.setIcon(null);
     IconPlan.setIcon(null);
     
}
    private void PanelControlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelControlMouseEntered
        IconControl.setForeground(new Color(51,204,0));
    }//GEN-LAST:event_PanelControlMouseEntered

    private void PanelControlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelControlMouseExited
        IconControl.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PanelControlMouseExited

    private void btnCerrarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMenuMouseExited
        btnCerrarMenu.setForeground(Color.BLACK);
        btnCerrarMenu.setBorder(null);
    }//GEN-LAST:event_btnCerrarMenuMouseExited

    private void btnCerrarMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMenuMouseEntered
        btnCerrarMenu.setForeground(Color.RED);
        btnCerrarMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
    }//GEN-LAST:event_btnCerrarMenuMouseEntered

    private void btnCerrarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMenuMouseClicked
        btnCerrarMenu.setForeground(null);
        dispose();
    }//GEN-LAST:event_btnCerrarMenuMouseClicked

    private void miniMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuMouseExited
        miniMenu.setForeground(Color.BLACK);
        miniMenu.setBorder(null);
    }//GEN-LAST:event_miniMenuMouseExited

    private void miniMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuMouseEntered
        miniMenu.setForeground(Color.GREEN);
        miniMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
    }//GEN-LAST:event_miniMenuMouseEntered

    private void miniMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuMouseClicked
        miniMenu.setForeground(null);
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_miniMenuMouseClicked
    
    
    public JInternalFrame centrarVentana(JInternalFrame frame) {  
        
        Menu1.add(frame);
        Dimension dimension = Menu1.getSize();
        Dimension Dframe = frame.getSize();
        frame.setLocation((dimension.width - Dframe.width) / 2, (dimension.height - Dframe.height));
    
         frame.show();
        
        return frame;      
    }
/**
 * Busca si el frame del parametro esta abierto si es asi manda true y no se vuelve a abrir y si no esta abuerto es false entonces lo abre
 * @param jif
 * @return 
 */
    public boolean InternalFramesAbiertos(JInternalFrame jif){ 
     JInternalFrame [] jif_Activos = Menu1.getAllFrames(); 
 
     for (int i = 0; i < jif_Activos.length; i++) { 
         
          if (jif.getClass().isInstance(jif_Activos[i])) {                              
                return true;
          }else{
          jif_Activos[i].dispose();
          return false;
          }
     }
     return false;
}
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel IconClientes;
    public static javax.swing.JLabel IconControl;
    public static javax.swing.JLabel IconEmpleado;
    public static javax.swing.JLabel IconGuardar;
    public static javax.swing.JLabel IconIngreso;
    public static javax.swing.JLabel IconPlan;
    public static javax.swing.JLabel IconProductos;
    public static javax.swing.JLabel IconVentas;
    public static javax.swing.JDesktopPane Menu1;
    public static javax.swing.JPanel PanelClientes;
    public static javax.swing.JPanel PanelControl;
    public static javax.swing.JPanel PanelEmpleados;
    public static javax.swing.JPanel PanelGuardar;
    public static javax.swing.JPanel PanelIngreso;
    public static javax.swing.JPanel PanelPlan;
    public static javax.swing.JPanel PanelProducto;
    public static javax.swing.JPanel PanelVentas;
    public static javax.swing.JLabel btnCerrarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel miniMenu;
    public static javax.swing.JLabel txtNom;
    // End of variables declaration//GEN-END:variables

   /*class FondoPanel extends JPanel{
   private Image imagen;
   public void paint(Graphics g){
    imagen = new ImageIcon(getClass().getResource("/Img/2.jpg")).getImage();
    g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
    //setOpaque(false);
    
    super.paint(g);
   }
   
   }*/
}
