/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.danielcampos.redgym.proyecto;

import static com.danielcampos.redgym.proyecto.Menu.IconControl;
import static com.danielcampos.redgym.proyecto.Menu.Menu1;
import static com.danielcampos.redgym.proyecto.PlanesClientes.fechaActual;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import static java.time.temporal.ChronoUnit.DAYS;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static com.danielcampos.redgym.proyecto.PlanesClientes.cmbCliente;
import java.awt.Color;
import static com.danielcampos.redgym.proyecto.Menu.PanelGuardar;
import static com.danielcampos.redgym.proyecto.Menu.IconGuardar;
import static com.danielcampos.redgym.proyecto.Menu.PanelControl;

/**
 *
 * @author Daniel Gerardo Campos García Class Vencimiento creada para buscar los
 * vencimeintos de mensualidades de los clientes Variables: Excritura de camello
 * abreviando su tipo de componente seguido de su nombre de variable Metodos:
 * Exritura de camello (El nombre debe se ser sacado de la funcion que tiene el
 * metodo)
 *
 */
public class Vencimiento extends javax.swing.JInternalFrame  implements MetodosGraficar{

    public static String fechaActual() {
        Date fecha = new Date();
        DateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
        return formatofecha.format(fecha);

    }
    DefaultTableModel model;

    public Vencimiento() {

        initComponents();
        setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Se carga la tabla conforme la fecha ingresada
     */
    void cargarTabla() {
        
        java.sql.Date fechaInicio = MetodosGraficar.getFecha(fechaInicial);        
        java.sql.Date fechafin = MetodosGraficar.getFecha(fechaFinal);
        Color myColor = new Color(255, 255, 255);
        tablaVencimiento.setBackground(myColor);
        tablaVencimiento.getTableHeader().setBackground(new Color(51, 102, 0));
        tablaVencimiento.getTableHeader().setFont(new java.awt.Font("Times New Roman", 3, 18));
        tablaVencimiento.getTableHeader().setForeground(new Color(255, 255, 255));
        tablaVencimiento.getTableHeader().setOpaque(false);
        tablaVencimiento.getTableHeader().setEnabled(false);
        String[] titulos = {"User", "Nombre", "Apellidos", "Vencimiento"};
        model = new DefaultTableModel(null, titulos);
        Conexion cc = new Conexion();
        Connection cn = cc.Conexion();
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int colu;
        try {
            ps = cn.prepareStatement("SELECT UserName,Nombre,Apellidos,fechaPlan FROM Clientes WHERE fechaPlan BETWEEN '" + fechaInicio + "' and '" + fechafin + "'");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            colu = rsmd.getColumnCount();

            while (rs.next()) {
                Object[] fila = new Object[colu];
                for (int indice = 0; indice < colu; indice++) {
                    fila[indice] = rs.getString(indice + 1);
                }
                model.addRow(fila);
            }
            tablaVencimiento.setModel(model);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto = new JPanelWebCam.JPanelWebCam();
        txtTelA = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaInicial = new com.toedter.calendar.JDateChooser();
        cerrar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        btnComprar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEN = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVencimiento = new javax.swing.JTable();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        btnGraficar = new javax.swing.JPanel();
        txtGraficar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(751, 582));

        foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fotoLayout = new javax.swing.GroupLayout(foto);
        foto.setLayout(fotoLayout);
        fotoLayout.setHorizontalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        fotoLayout.setVerticalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        txtTelA.setEditable(false);
        txtTelA.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtTelA.setForeground(new java.awt.Color(255, 153, 0));
        txtTelA.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelA.setBorder(null);
        txtTelA.setDisabledTextColor(new java.awt.Color(255, 153, 0));
        txtTelA.setEnabled(false);
        txtTelA.setOpaque(false);

        txtNom.setEditable(false);
        txtNom.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtNom.setForeground(new java.awt.Color(255, 153, 0));
        txtNom.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNom.setBorder(null);
        txtNom.setDisabledTextColor(new java.awt.Color(255, 153, 0));
        txtNom.setEnabled(false);
        txtNom.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Nombre Cliente:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Telefono:");

        fechaInicial.setDateFormatString("yyyy-MM-dd");
        fechaInicial.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        fechaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaInicialMouseClicked(evt);
            }
        });

        cerrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Buscar.setForeground(new java.awt.Color(51, 204, 0));
        Buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Buscar.setText("Buscar");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        btnComprar.setBackground(new java.awt.Color(102, 204, 0));
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprarMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Comprar Plan");

        javax.swing.GroupLayout btnComprarLayout = new javax.swing.GroupLayout(btnComprar);
        btnComprar.setLayout(btnComprarLayout);
        btnComprarLayout.setHorizontalGroup(
            btnComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnComprarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        btnComprarLayout.setVerticalGroup(
            btnComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vencimientos");

        btnEN.setBackground(new java.awt.Color(255, 255, 255));
        btnEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnENMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnENMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnENMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(">");

        javax.swing.GroupLayout btnENLayout = new javax.swing.GroupLayout(btnEN);
        btnEN.setLayout(btnENLayout);
        btnENLayout.setHorizontalGroup(
            btnENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnENLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );
        btnENLayout.setVerticalGroup(
            btnENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnENLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tablaVencimiento.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tablaVencimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaVencimiento.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaVencimiento.setOpaque(false);
        tablaVencimiento.setSelectionBackground(new java.awt.Color(51, 102, 0));
        tablaVencimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVencimientoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVencimiento);

        fechaFinal.setDateFormatString("yyyy-MM-dd");
        fechaFinal.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        fechaFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaFinalMouseClicked(evt);
            }
        });

        btnGraficar.setBackground(new java.awt.Color(255, 255, 255));
        btnGraficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraficarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGraficarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGraficarMouseExited(evt);
            }
        });

        txtGraficar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        txtGraficar.setForeground(new java.awt.Color(0, 153, 255));
        txtGraficar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGraficar.setText("Graficar");

        javax.swing.GroupLayout btnGraficarLayout = new javax.swing.GroupLayout(btnGraficar);
        btnGraficar.setLayout(btnGraficarLayout);
        btnGraficarLayout.setHorizontalGroup(
            btnGraficarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGraficarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGraficar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnGraficarLayout.setVerticalGroup(
            btnGraficarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGraficar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNom)
                            .addComponent(txtTelA))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(cerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
        Color cl = new Color(0, 117, 155);
        PanelControl.setBackground(cl);

        IconControl.setIcon(null);
        PanelControl.setEnabled(true);
    }//GEN-LAST:event_cerrarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        cargarTabla();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseClicked
        PlanesClientes pc = new PlanesClientes();
        centrarVentana(pc);

    }//GEN-LAST:event_btnComprarMouseClicked

    private void btnENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnENMouseClicked
        dispose();
        EntradasYSalidas cn = new EntradasYSalidas();
        centrarVentana(cn);
    }//GEN-LAST:event_btnENMouseClicked

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(102, 204, 0));
        Buscar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(255, 255, 255));
        Buscar.setForeground(new Color(51, 204, 0));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseEntered
        btnComprar.setBackground(new Color(51, 153, 0));

    }//GEN-LAST:event_btnComprarMouseEntered

    private void btnComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseExited
        btnComprar.setBackground(new Color(102, 204, 0));
    }//GEN-LAST:event_btnComprarMouseExited

    private void tablaVencimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVencimientoMouseClicked
        try {
            int fila = tablaVencimiento.getSelectedRow();
            int id = Integer.parseInt(tablaVencimiento.getValueAt(fila, 0).toString());

            Conexion cc = new Conexion();
            PreparedStatement ps;
            ResultSet rs;
            Connection cn = cc.Conexion();

            ps = cn.prepareStatement("SELECT UserName,Nombre,Telefono,Fotografia FROM Clientes WHERE UserName=?");
            ps.setInt(1, id);
            rs = ps.executeQuery();
            while (rs.next()) {

                txtNom.setText(rs.getString("Nombre"));
                txtTelA.setText(rs.getString("Telefono"));
                byte[] imagen = rs.getBytes("Fotografia");
                foto.setImagen(imagen);
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
    }//GEN-LAST:event_tablaVencimientoMouseClicked

    private void btnENMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnENMouseEntered
        btnEN.setBackground(new Color(0, 240, 0));
    }//GEN-LAST:event_btnENMouseEntered

    private void btnENMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnENMouseExited
        btnEN.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnENMouseExited

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        cerrar.setForeground(Color.RED);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        cerrar.setForeground(Color.BLACK);
    }//GEN-LAST:event_cerrarMouseExited

    private void fechaFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaFinalMouseClicked

    }//GEN-LAST:event_fechaFinalMouseClicked

    private void fechaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaInicialMouseClicked

    }//GEN-LAST:event_fechaInicialMouseClicked

    private void btnGraficarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficarMouseClicked
        java.sql.Date fechaInicio = MetodosGraficar.getFecha(fechaInicial);        
        java.sql.Date fechafin = MetodosGraficar.getFecha(fechaFinal);
        MetodosGraficar.graficaBarrasVencimiento(fechaInicio, fechafin);
    }//GEN-LAST:event_btnGraficarMouseClicked

    private void btnGraficarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficarMouseEntered
        btnGraficar.setBackground(new Color(0,153,255));
        txtGraficar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnGraficarMouseEntered

    private void btnGraficarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficarMouseExited
        btnGraficar.setBackground(new Color(255, 255, 255));
        txtGraficar.setForeground(new Color(0,153,255));
    }//GEN-LAST:event_btnGraficarMouseExited
    /**
     * Este metodo es para abrir un JInternalFrame centrado en un JDesktop panel
     *
     * @param frame
     */
    void centrarVentana(JInternalFrame frame) {

        Menu1.add(frame);
        Dimension dimension = Menu1.getSize();
        Dimension Dframe = frame.getSize();
        frame.setLocation((dimension.width - Dframe.width) / 2, (dimension.height - Dframe.height));
        frame.show();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Buscar1;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnBuscar1;
    private javax.swing.JPanel btnComprar;
    private javax.swing.JPanel btnEN;
    private javax.swing.JPanel btnGraficar;
    private javax.swing.JLabel cerrar;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicial;
    private JPanelWebCam.JPanelWebCam foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaVencimiento;
    private javax.swing.JLabel txtGraficar;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTelA;
    // End of variables declaration//GEN-END:variables

}
